ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.pmpkdev.online
CATALOGUE_HOST: catalogue-dev.pmpkdev.online
REDIS_HOST: redis-dev.pmpkdev.online
USER_HOST: user-dev.pmpkdev.online
CART_HOST: cart-dev.pmpkdev.online
MYSQL_HOST: mysql-dev.pmpkdev.online
SHIPPING_HOST: shipping-dev.pmpkdev.online
RABBITMQ_HOST: rabbitmq-dev.pmpkdev.online
PAYMENT_HOST: payment-dev.pmpkdev.online