$ANSIBLE_VAULT;1.1;AES256
37613836373135623934653935386466666262383032336164643165376562313934393261666337
3465633063303339623961333236343432663762666230340a656339343637363864646464313937
33643339386333626330666563306131363562633565353462346263666232393331386537333636
3437613834303666320a313032306438613364613464356561353466626164666534343138663265
62393030323838363034346537343631393737313939396165353365666636663232666265353361
6234633934336666646237333263396465366461633932376131