- name: install maven and mysql
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - maven
  - mysql
  
- name: Install dependencies
  ansible.builtin.command: mvn clean package 
  args: 
    chdir: /app

- name: Rename jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
  args: 
    chdir: /app